/**
 * Cloudflare Worker Reverse Proxy for Discord Activity (pstream.cfd)
 *
 * This worker:
 * 1. Universal Gateway (`/z-*` prefix): Proxies /z-tmdb, /z-image, /z-court,
 *    /z-justice, /z-aurora, /z-natsuki, /z-artemis (+ legacy /tmdb, /court, etc.)
 * 2. Header Sanitization: Strips CF-*, X-Forwarded-*, Host, Origin, Referer, Cookie
 *    before egress. We do NOT re-add Origin/Referer — doing so causes HTTP 525
 *    SSL Handshake Failed on Cloudflare-to-Cloudflare requests.
 * 3. Runtime Interceptor: Prepended to every HTML and JS file so that absolute
 *    TMDB/Fontaine URLs are rewritten to relative /z-* paths before the browser
 *    sees them — bypassing Discord Activity's strict img-src CSP.
 * 4. Nonce forwarding: We extract the CSP nonce from the page's existing scripts
 *    and apply it to our injected <script> so Discord's CSP doesn't block it.
 * 5. TMDB fallback: If api.themoviedb.org returns 5xx, retry via api.tmdb.org.
 */

import RUNTIME_INTERCEPTOR from './interceptor.js';

// ── Route table ───────────────────────────────────────────────────────────────

const ROUTES = [
  { prefixes: ['/z-tmdb/', '/z-tmdb', '/tmdb/', '/tmdb'],   origin: 'https://api.themoviedb.org', strip: /^\/(z-)?tmdb/ },
  { prefixes: ['/z-image/', '/z-image', '/image-tmdb/', '/image-tmdb'], origin: 'https://image.tmdb.org',    strip: /^\/(z-image|image-tmdb)/ },
  { prefixes: ['/z-sync/', '/z-sync', '/sync/', '/sync'],      origin: 'https://sync.pstream.cfd',     strip: /^\/(z-)?sync/ },
  { prefixes: ['/z-court/', '/z-court', '/court/', '/court'],  origin: 'https://court.fontaine.lol',   strip: /^\/(z-)?court/ },
  { prefixes: ['/z-justice/', '/z-justice', '/justice/', '/justice'], origin: 'https://justice.fontaine.lol', strip: /^\/(z-)?justice/ },
  { prefixes: ['/z-aurora/', '/z-aurora', '/aurora/', '/aurora'],  origin: 'https://aurora.fontaine.lol',  strip: /^\/(z-)?aurora/ },
  { prefixes: ['/z-natsuki/', '/z-natsuki', '/natsuki/', '/natsuki'], origin: 'https://natsuki.fontaine.lol', strip: /^\/(z-)?natsuki/ },
  { prefixes: ['/z-artemis/', '/z-artemis', '/artemis/', '/artemis'], origin: 'https://artemis.fontaine.lol', strip: /^\/(z-)?artemis/ },
  // Stream source domains returned by providers after scraping — all blocked by connect-src CSP
  // unless proxied through our worker's /z-* paths.
  { prefixes: ['/z-stream/', '/z-stream'], origin: 'https://stream.fontaine.lol',  strip: /^\/z-stream/ },
  { prefixes: ['/z-cdn/',    '/z-cdn'],    origin: 'https://cdn.fontaine.lol',     strip: /^\/z-cdn/ },
  { prefixes: ['/z-tokyo/',  '/z-tokyo'],  origin: 'https://tokyo.fontaine.lol',   strip: /^\/z-tokyo/ },
  // strm.fontaine.lol — the actual HLS CDN that providers return in their sources
  { prefixes: ['/z-strm/',   '/z-strm'],   origin: 'https://strm.fontaine.lol',    strip: /^\/z-strm/ },
  { prefixes: ['/z-introdb/', '/z-introdb'], origin: 'https://api.theintrodb.org', strip: /^\/z-introdb/ },
  { prefixes: ['/z-encdec/', '/z-encdec'], origin: 'https://enc-dec.app',          strip: /^\/z-encdec/ },
  // Additional metadata domains
  { prefixes: ['/z-balloon/', '/z-balloon'], origin: 'https://api.balloonerismm.workers.dev', strip: /^\/z-balloon/ },
  { prefixes: ['/z-jw-api/', '/z-jw-api'],   origin: 'https://apis.justwatch.com',          strip: /^\/z-jw-api/ },
  { prefixes: ['/z-jw-img/', '/z-jw-img'],   origin: 'https://images.justwatch.com',        strip: /^\/z-jw-img/ },
  { prefixes: ['/z-debrid/', '/z-debrid'],   origin: 'https://api.real-debrid.com',         strip: /^\/z-debrid/ },
];

// Fallback origin for TMDB (used when api.themoviedb.org returns 5xx)
const TMDB_FALLBACK_ORIGIN = 'https://api.tmdb.org';

// ── Worker ────────────────────────────────────────────────────────────────────

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);

    // Extract consistent spoofed IP generated by the interceptor
    let spoofedIp = url.searchParams.get('z_ip');
    if (spoofedIp) {
      url.searchParams.delete('z_ip'); // Remove from search params so it doesn't leak upstream
    } else {
      spoofedIp = '73.194.22.115'; // Fallback consistent IP if not provided
    }

    const originHeader = request.headers.get('Origin') || '*';
    const reqHeaders = request.headers.get('Access-Control-Request-Headers') || '*';

    // CORS preflight
    if (request.method === 'OPTIONS') {
      return new Response(null, {
        status: 204,
        headers: {
          'Access-Control-Allow-Origin': originHeader,
          'Access-Control-Allow-Credentials': 'true',
          'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS',
          'Access-Control-Allow-Headers': reqHeaders,
          'Access-Control-Max-Age': '86400',
        },
      });
    }

    // Client logger endpoint
    if (url.pathname === '/z-log') {
      let logMsg = '';
      if (request.method === 'POST') {
        try {
          const body = await request.json();
          logMsg = body.log || '';
        } catch(e) {
          logMsg = await request.text();
        }
      } else if (request.method === 'GET') {
        logMsg = url.searchParams.get('msg') || '';
      }
      console.log('[CLIENT LOG]', logMsg);
      return new Response('ok', { headers: { 'Access-Control-Allow-Origin': '*' } });
    }

    // Serve interceptor as external script so inline HTML injection only inserts
    // a tiny <script src> tag — prevents interceptor source from appearing as
    // visible text when the player error handler reads innerHTML.
    if (url.pathname === '/z-interceptor.js') {
      return new Response(RUNTIME_INTERCEPTOR, {
        headers: {
          'Content-Type': 'application/javascript; charset=utf-8',
          'Access-Control-Allow-Origin': '*',
          'Cache-Control': 'no-cache, no-store, must-revalidate',
        },
      });
    }

    // Determine target origin and path
    let targetOrigin = 'https://pstream.cfd';
    let targetPathname = url.pathname;
    let isTmdb = false;
    let targetUrl;

    if (url.pathname.startsWith('/z-ext/')) {
      let extUrlStr = url.searchParams.get('u');
      
      if (!extUrlStr) {
        // Try parsing from base64 path: /z-ext/<b64>/<relative>
        const parts = url.pathname.split('/');
        if (parts.length >= 3 && parts[2]) {
          try {
            const b64 = parts[2];
            // If it's a valid b64, it won't contain '%', which is used in encodeURIComponent fallback
            if (!b64.includes('%')) {
              const decodedBase = decodeURIComponent(escape(atob(b64.replace(/-/g, '+').replace(/_/g, '/'))));
              // Reconstruct the intended relative path
              const relativePath = parts.slice(3).join('/') + url.search;
              extUrlStr = new URL(relativePath, decodedBase).toString();
            } else {
              const decodedBase = decodeURIComponent(b64);
              const relativePath = parts.slice(3).join('/') + url.search;
              extUrlStr = new URL(relativePath, decodedBase).toString();
            }
          } catch(e) {}
        }
      }

      if (!extUrlStr) {
        const referer = request.headers.get('Referer');
        if (referer && referer.includes('/z-ext/')) {
          try {
            const refUrl = new URL(referer);
            const refParts = refUrl.pathname.split('/');
            let refU = refUrl.searchParams.get('u');
            if (!refU && refParts.length >= 3 && refParts[2]) {
              const b64 = refParts[2];
              if (!b64.includes('%')) {
                refU = decodeURIComponent(escape(atob(b64.replace(/-/g, '+').replace(/_/g, '/'))));
              } else {
                refU = decodeURIComponent(b64);
              }
            }
            if (refU) {
              const relativePath = url.pathname.replace(/^\/z-ext\/?/, '') + url.search;
              extUrlStr = new URL(relativePath, refU).toString();
            }
          } catch(e) {}
        }
      }

      if (extUrlStr) {
        try {
          targetUrl = new URL(extUrlStr);
          targetOrigin = targetUrl.origin;
          targetPathname = targetUrl.pathname;
        } catch (e) {
          return new Response('Invalid z-ext URL', { status: 400 });
        }
      } else {
        return new Response('Missing target parameter or invalid path', { status: 400 });
      }
    } else {
      for (const route of ROUTES) {
        for (const prefix of route.prefixes) {
          if (url.pathname === prefix || url.pathname.startsWith(prefix.endsWith('/') ? prefix : prefix + '/')) {
            targetOrigin = route.origin;
            targetPathname = url.pathname.replace(route.strip, '') || '/';
            isTmdb = route.origin.includes('themoviedb') || route.origin.includes('tmdb.org');
            break;
          }
        }
        if (targetOrigin !== 'https://pstream.cfd') break;
      }
      targetUrl = new URL(targetPathname + url.search, targetOrigin);
    }

    // Build sanitized headers — strip Host, Origin, Referer, Cookie, CF-*, X-Forwarded-*, Sec-*
    // CRITICAL: We also strip conditional headers (If-None-Match, If-Modified-Since) when fetching
    // from pstream.cfd so upstream never returns 304 Not Modified. This guarantees our worker
    // always modifies HTML/JS bundles and injects the latest interceptor version.
    const cleanHeaders = new Headers();
    for (const [key, value] of request.headers.entries()) {
      const lower = key.toLowerCase();
      if (lower.startsWith('cf-') || lower === 'host' || lower === 'origin' ||
          lower === 'referer' ||
          lower === 'if-none-match' || lower === 'if-modified-since' || lower === 'if-range' ||
          lower.startsWith('x-forwarded') || lower.startsWith('sec-')) {
        continue;
      }
      cleanHeaders.set(key, value);
    }
    // Always spoof Origin and Referer to the main domain so upstream doesn't block hotlinking.
    cleanHeaders.set('Origin', 'https://pstream.cfd');
    cleanHeaders.set('Referer', 'https://pstream.cfd/');
    
    let ua = request.headers.get('User-Agent') || 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';
    ua = ua.replace(/Discord[\w.-]*\/\d+[\.\d]*\s*/g, '');
    cleanHeaders.set('User-Agent', ua);

    // Pass the spoofed IP so backend providers don't block changing Discord proxy IPs
    // The interceptor ensures this IP is consistent across API calls and video segments.
    cleanHeaders.set('True-Client-IP', spoofedIp);
    cleanHeaders.set('X-Forwarded-For', spoofedIp);
    cleanHeaders.set('X-Real-IP', spoofedIp);
    cleanHeaders.set('X-Client-IP', spoofedIp);
    cleanHeaders.set('Forwarded', `for=${spoofedIp}`);

    // Upstream fetch with TMDB fallback on 5xx
    async function upstreamFetch(origin, pathname) {
      let fetchUrl;
      if (url.pathname.startsWith('/z-ext/')) {
        fetchUrl = targetUrl;
      } else {
        fetchUrl = new URL(pathname + url.search, origin);
      }
      return fetch(fetchUrl.toString(), {
        method: request.method,
        headers: cleanHeaders,
        body: ['GET', 'HEAD'].includes(request.method) ? null : request.body,
        redirect: 'follow',
      });
    }

    let response;
    try {
      response = await upstreamFetch(targetOrigin, targetPathname);

      // If TMDB primary returns 5xx, retry with the alternate base URL
      if (isTmdb && response.status >= 500) {
        try {
          const fallbackOrigin = targetOrigin.includes('themoviedb')
            ? TMDB_FALLBACK_ORIGIN
            : 'https://api.themoviedb.org';
          const fallback = await upstreamFetch(fallbackOrigin, targetPathname);
          if (fallback.status < 500) response = fallback;
        } catch(e) { /* keep original response */ }
      }
    } catch (err) {
      return new Response(`Proxy upstream error: ${err.message}`, { status: 502 });
    }

    // Build response headers
    const responseHeaders = new Headers(response.headers);
    responseHeaders.delete('X-Frame-Options');
    responseHeaders.delete('Content-Security-Policy');
    responseHeaders.set('Access-Control-Allow-Origin', originHeader);
    responseHeaders.set('Access-Control-Allow-Credentials', 'true');
    responseHeaders.set('Access-Control-Expose-Headers', 'Content-Length, Content-Range, Content-Type, Accept-Ranges, Date, ETag, Last-Modified');
    responseHeaders.set('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, OPTIONS');
    responseHeaders.set('Access-Control-Allow-Headers', reqHeaders);

    // Disable caching for the Sync API so Watch Party polling isn't cached by Discord's proxy
    if (targetOrigin === 'https://sync.pstream.cfd') {
      responseHeaders.set('Cache-Control', 'no-cache, no-store, must-revalidate');
      responseHeaders.delete('ETag');
      responseHeaders.delete('Last-Modified');
    }

    const contentType = response.headers.get('content-type') || '';
    const isHtml = contentType.includes('text/html');
    const isJs   = contentType.includes('application/javascript') || contentType.includes('text/javascript');

    if (isHtml && response.status === 200) {
      responseHeaders.delete('Content-Encoding'); // We uncompress HTML text here
      let text = await response.text();
      // Delete ETag and Last-Modified so Discord's proxy / browser never caches modified HTML or JS bundles
      responseHeaders.delete('ETag');
      responseHeaders.delete('Last-Modified');
      responseHeaders.set('Cache-Control', 'no-cache, no-store, must-revalidate');

      if (isHtml) {
        // Strip SRI integrity attrs (our JS injection invalidates them)
        text = text.replace(/\s*integrity=["'][^"']*["']/gi, '');

        // Extract existing CSP nonce so our injected <script> isn't blocked
        // Discord's embed proxy sets:  script-src 'self' 'unsafe-eval' 'nonce-XXXX' blob:
        // Our script MUST carry that nonce or it will be rejected.
        let nonce = '';
        const nonceMatch = text.match(/\bnonce="([^"]+)"/i) || text.match(/\bnonce='([^']+)'/i);
        if (nonceMatch) nonce = nonceMatch[1];

        const nonceAttr = nonce ? ` nonce="${nonce}"` : '';
        const scriptTag = `<script src="/z-interceptor.js"${nonceAttr}></script>`;

        if (/<head[^>]*>/i.test(text)) {
          text = text.replace(/(<head[^>]*>)/i, `$1\n${scriptTag}`);
        } else {
          text = scriptTag + text;
        }
      }
      // NOTE: We intentionally do NOT inject into JS files.
      // The <head> injection above runs first and patches fetch/XHR/URL
      // before any app JS executes. Prepending to every JS bundle corrupts
      // dynamic module loading and causes the interceptor source to appear as text.

      if (targetOrigin !== 'https://pstream.cfd') {
        const baseUrl = response.url;
        class AttributeRewriter {
          element(el) {
            for (const attr of ['src', 'href', 'data-src', 'poster', 'action']) {
              const val = el.getAttribute(attr);
              if (val && !val.startsWith('data:') && !val.startsWith('blob:')) {
                try {
                  const absUrl = new URL(val, baseUrl).toString();
                  el.setAttribute(attr, '/z-ext/?u=' + encodeURIComponent(absUrl) + (spoofedIp ? '&z_ip=' + spoofedIp : ''));
                } catch(e) {}
              }
            }
          }
        }
        
        let rwResponse = new Response(text, { status: response.status, statusText: response.statusText, headers: responseHeaders });
        const rewriter = new HTMLRewriter()
          .on('script', new AttributeRewriter())
          .on('link', new AttributeRewriter())
          .on('img', new AttributeRewriter())
          .on('iframe', new AttributeRewriter())
          .on('video', new AttributeRewriter())
          .on('source', new AttributeRewriter())
          .on('form', new AttributeRewriter());
          
        return rewriter.transform(rwResponse);
      }

      return new Response(text, {
        status: response.status,
        statusText: response.statusText,
        headers: responseHeaders,
      });
    }

    const isM3u8 = contentType.includes('mpegurl') || targetPathname.endsWith('.m3u8');

    if (isM3u8 && response.status === 200) {
      responseHeaders.delete('Content-Encoding'); // We uncompress M3u8 text here
      let text = await response.text();
      // Rewrite relative paths to absolute URLs based on the final response.url
      const baseUrl = response.url;
      text = text.split('\n').map(line => {
        const trimmed = line.trim();
        if (trimmed && !trimmed.startsWith('#') && !trimmed.startsWith('data:')) {
          try {
            let absUrl = trimmed;
            if (!trimmed.startsWith('http://') && !trimmed.startsWith('https://')) {
              absUrl = new URL(trimmed, baseUrl).toString();
            }
            let encodedU = btoa(unescape(encodeURIComponent(absUrl))).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
            return '/z-ext/' + encodedU + '/?z_ip=' + spoofedIp;
          } catch(e) {
            return line;
          }
        }
        // Also rewrite URIs inside tags like #EXT-X-KEY:METHOD=AES-128,URI="key.bin"
        if (trimmed.startsWith('#EXT-X-') && trimmed.includes('URI="')) {
          return line.replace(/URI="([^"]+)"/, (match, uri) => {
            if (!uri.startsWith('data:')) {
              try {
                let absUrl = uri;
                if (!uri.startsWith('http://') && !uri.startsWith('https://')) {
                  absUrl = new URL(uri, baseUrl).toString();
                }
                return `URI="/z-ext/?u=${encodeURIComponent(absUrl)}&z_ip=${spoofedIp}"`;
              } catch(e) {
                return match;
              }
            }
            return match;
          });
        }
        return line;
      }).join('\n');
      
      responseHeaders.delete('Content-Length');
      return new Response(text, {
        status: response.status,
        statusText: response.statusText,
        headers: responseHeaders,
      });
    }

    return new Response(response.body, {
      status: response.status,
      statusText: response.statusText,
      headers: responseHeaders,
    });
  },
};
